#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# Values are remembered here between runs so a Ctrl-C costs nothing. None of
# them is a secret — a project id, two service account emails and a provider
# path — but they are local machine state rather than repository content, so
# the file is git-ignored. The one actual secret this creates never leaves
# Google: it is piped from `openssl` straight into Secret Manager and is not
# printed, echoed or written down at any point.
ENV_FILE=".gcp-deploy.env"

GH_REPO="Xeno828/delivery-value-dashboard"
AR_REPO="calculator"
REGIONS="us-central1 europe-west3"
POOL="github"
PROVIDER="github"
SECRET_NAME="calculator-shared-secret"

# `set -e` aborts on the first non-zero exit, which is what you want everywhere
# except a create that has already been done. Re-running this wizard must be
# free, so creates are guarded by their own describe.
exists() { "$@" >/dev/null 2>&1; }

TOTAL_STAGES=8

banner "Host the calculator: Google Cloud provisioning"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Tools"
say "Two command-line tools do the work: gcloud creates everything in Google"
say "Cloud, and gh writes the results into this repository's Actions variables."
printf '\n'

if command -v gcloud >/dev/null 2>&1; then
  note "gcloud $(gcloud --version 2>/dev/null | head -1 | awk '{print $NF}') found"
else
  warn "gcloud is not installed, and nothing below works without it."
  open_url "https://cloud.google.com/sdk/docs/install"
  step "Install the Google Cloud CLI for macOS, then open a NEW terminal."
  step "Re-run this wizard: bash service/provision-gcp.sh"
  printf '\n'
  exit 1
fi

if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  note "gh authenticated as $(gh api user --jq .login 2>/dev/null || echo '?')"
else
  warn "gh is missing or not logged in. The wizard will still create everything"
  warn "in Google Cloud and will print the variables for you to add by hand."
fi
printf '\n'
pause "Press Enter to continue"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Sign in, and choose the project"
say "The calculator wants its own project. A shared one works, but a dedicated"
say "project makes the bill, the IAM policy and the audit log all readable."
printf '\n'

if [[ -z "$(gcloud auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null)" ]]; then
  step "A browser will open. Sign in with the Google account that owns the billing."
  pause "Press Enter to open it"
  gcloud auth login
else
  note "signed in as $(gcloud auth list --filter=status:ACTIVE --format='value(account)' | head -1)"
fi

printf '\n'
say "Projects on this account:"
gcloud projects list --format='table(projectId,name,projectNumber)' 2>/dev/null | sed 's/^/    /' || true
printf '\n'
note "If the list is empty, or you want a new one, create it here and come back:"
note "  https://console.cloud.google.com/projectcreate"
printf '\n'
ask GCP_PROJECT_ID "Project ID to deploy into:"
[[ -n "$GCP_PROJECT_ID" ]] || { warn "no project id given"; exit 1; }
gcloud config set project "$GCP_PROJECT_ID" >/dev/null
write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"

GCP_PROJECT_NUMBER=$(gcloud projects describe "$GCP_PROJECT_ID" --format='value(projectNumber)')
write_env GCP_PROJECT_NUMBER "$GCP_PROJECT_NUMBER"

printf '\n'
BILLING=$(gcloud billing projects describe "$GCP_PROJECT_ID" \
            --format='value(billingEnabled)' 2>/dev/null || echo "unknown")
if [[ "$BILLING" == "True" ]]; then
  note "billing is enabled"
else
  warn "billing does not look enabled (reported: $BILLING)."
  warn "Enabling the APIs in the next stage will fail without it."
  note "At the volumes in docs/hosting-the-calculator.md this project is expected"
  note "to cost under \$4/month, and \$0 until something calls it — but a card"
  note "has to be on file all the same."
  open_url "https://console.cloud.google.com/billing/linkedaccount?project=$GCP_PROJECT_ID"
  pause "Link a billing account, then press Enter"
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Enable the APIs"
say "Six, and each is used: Cloud Run to serve, Artifact Registry to hold the"
say "image, IAM Credentials and STS to exchange GitHub's OIDC token for a"
say "short-lived Google one, Secret Manager for the temporary shared secret,"
say "and Resource Manager for the IAM bindings."
printf '\n'
note "This takes a minute or two and is safe to re-run."
printf '\n'
if confirm "Enable them on $GCP_PROJECT_ID?"; then
  gcloud services enable \
    run.googleapis.com \
    artifactregistry.googleapis.com \
    iamcredentials.googleapis.com \
    sts.googleapis.com \
    secretmanager.googleapis.com \
    cloudresourcemanager.googleapis.com \
    --project="$GCP_PROJECT_ID"
  printf '  %s✓%s enabled\n' "$GREEN" "$RESET"
else
  warn "skipped — nothing after this will work until they are enabled"
  exit 1
fi
printf '\n'
pause "Press Enter to continue"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Artifact Registry, one repository per region"
say "One repository in each region the service runs in, so a cold start pulls"
say "its image from the same region rather than across the Atlantic. Cold-start"
say "latency is a correctness concern here, not just a slow tile: the Forge"
say "invocation token lives about 25 seconds and the remote timeout is 25s."
printf '\n'
for region in $REGIONS; do
  if exists gcloud artifacts repositories describe "$AR_REPO" \
       --location="$region" --project="$GCP_PROJECT_ID"; then
    note "$region/$AR_REPO already exists"
  else
    gcloud artifacts repositories create "$AR_REPO" \
      --repository-format=docker \
      --location="$region" \
      --project="$GCP_PROJECT_ID" \
      --description="The delivery-value-dashboard calculator (service/Dockerfile)"
    printf '  %s✓%s created %s/%s\n' "$GREEN" "$RESET" "$region" "$AR_REPO"
  fi
done
printf '\n'
pause "Press Enter to continue"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Two service accounts, and why it is two"
say "The account CI uses to deploy and the account the container runs as are"
say "different identities on purpose. The deployer may push images and update"
say "services; it may not read the secret. The runtime may read the one secret"
say "it needs; it may not deploy anything. Neither can do the other's job, so"
say "neither is worth stealing for the other's sake."
printf '\n'

GCP_DEPLOY_SA="calculator-deploy@${GCP_PROJECT_ID}.iam.gserviceaccount.com"
GCP_RUNTIME_SA="calculator-run@${GCP_PROJECT_ID}.iam.gserviceaccount.com"

for pair in "calculator-deploy:deploys from GitHub Actions" \
            "calculator-run:the identity the container runs as"; do
  name="${pair%%:*}"; desc="${pair#*:}"
  if exists gcloud iam service-accounts describe \
       "${name}@${GCP_PROJECT_ID}.iam.gserviceaccount.com" --project="$GCP_PROJECT_ID"; then
    note "$name already exists"
  else
    gcloud iam service-accounts create "$name" \
      --display-name="calculator — $desc" --project="$GCP_PROJECT_ID"
    printf '  %s✓%s created %s\n' "$GREEN" "$RESET" "$name"
  fi
done

printf '\n'
say "Granting the deployer exactly three things:"
for role in roles/run.admin roles/artifactregistry.writer; do
  step "$role"
  gcloud projects add-iam-policy-binding "$GCP_PROJECT_ID" \
    --member="serviceAccount:${GCP_DEPLOY_SA}" --role="$role" \
    --condition=None >/dev/null
done
step "roles/iam.serviceAccountUser, on the runtime account only"
gcloud iam service-accounts add-iam-policy-binding "$GCP_RUNTIME_SA" \
  --member="serviceAccount:${GCP_DEPLOY_SA}" \
  --role="roles/iam.serviceAccountUser" \
  --project="$GCP_PROJECT_ID" >/dev/null

note "that last one is scoped to the runtime account rather than the project,"
note "so the deployer can run the service as it and as nothing else"

write_env GCP_DEPLOY_SA "$GCP_DEPLOY_SA"
write_env GCP_RUNTIME_SA "$GCP_RUNTIME_SA"
printf '\n'
pause "Press Enter to continue"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Workload Identity Federation"
say "This is what lets GitHub Actions deploy without a key existing anywhere."
say "GitHub mints a short-lived OIDC token describing which repository is"
say "running; Google exchanges it for a short-lived access token. Nothing"
say "long-lived is stored in the repository, so there is no key to leak and"
say "none to rotate."
printf '\n'
warn "The attribute condition below is the entire security control."
note "Without it, ANY GitHub repository's token would be accepted and could"
note "deploy to this project. It pins the trust to $GH_REPO."
printf '\n'
if confirm "Create the pool and provider, trusting only $GH_REPO?"; then
  if exists gcloud iam workload-identity-pools describe "$POOL" \
       --location=global --project="$GCP_PROJECT_ID"; then
    note "pool '$POOL' already exists"
  else
    gcloud iam workload-identity-pools create "$POOL" \
      --location=global --display-name="GitHub Actions" \
      --project="$GCP_PROJECT_ID"
  fi

  if exists gcloud iam workload-identity-pools providers describe "$PROVIDER" \
       --location=global --workload-identity-pool="$POOL" --project="$GCP_PROJECT_ID"; then
    note "provider '$PROVIDER' already exists — leaving its condition untouched"
    note "(if you need to change the repository it trusts, delete and re-create it)"
  else
    gcloud iam workload-identity-pools providers create-oidc "$PROVIDER" \
      --location=global \
      --workload-identity-pool="$POOL" \
      --display-name="GitHub Actions OIDC" \
      --issuer-uri="https://token.actions.githubusercontent.com" \
      --attribute-mapping="google.subject=assertion.sub,attribute.repository=assertion.repository,attribute.repository_owner=assertion.repository_owner" \
      --attribute-condition="assertion.repository=='${GH_REPO}'" \
      --project="$GCP_PROJECT_ID"
    printf '  %s✓%s provider created, pinned to %s\n' "$GREEN" "$RESET" "$GH_REPO"
  fi
else
  warn "skipped — CI cannot authenticate without this"
  exit 1
fi

printf '\n'
say "Letting that repository impersonate the deploy account, and only it:"
gcloud iam service-accounts add-iam-policy-binding "$GCP_DEPLOY_SA" \
  --role="roles/iam.workloadIdentityUser" \
  --member="principalSet://iam.googleapis.com/projects/${GCP_PROJECT_NUMBER}/locations/global/workloadIdentityPools/${POOL}/attribute.repository/${GH_REPO}" \
  --project="$GCP_PROJECT_ID" >/dev/null

GCP_WIF_PROVIDER="projects/${GCP_PROJECT_NUMBER}/locations/global/workloadIdentityPools/${POOL}/providers/${PROVIDER}"
write_env GCP_WIF_PROVIDER "$GCP_WIF_PROVIDER"
printf '\n'
pause "Press Enter to continue"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "The shared secret, which is temporary by design"
say "The first deployment runs in SERVICE_AUTH=shared-secret so that hosting"
say "can be proved on its own — a curl against the public URL returning a real"
say "forecast, before Forge is anywhere near it. Otherwise the first test of"
say "the deployment is also the first test of the Forge wiring, and a failure"
say "could be either."
printf '\n'
note "It is generated by openssl, piped straight into Secret Manager, and is"
note "never printed here or written to disk. Nobody needs to know its value."
note "It is deleted at step 5 of docs/hosting-the-calculator.md §13, when the"
note "service moves to forge-token and stops holding any secret at all."
printf '\n'

if exists gcloud secrets describe "$SECRET_NAME" --project="$GCP_PROJECT_ID"; then
  note "$SECRET_NAME already exists — leaving the existing value alone"
else
  openssl rand -hex 32 | gcloud secrets create "$SECRET_NAME" \
    --data-file=- --replication-policy=automatic --project="$GCP_PROJECT_ID"
  printf '  %s✓%s created %s\n' "$GREEN" "$RESET" "$SECRET_NAME"
fi

say "Granting the runtime account read on that one secret:"
gcloud secrets add-iam-policy-binding "$SECRET_NAME" \
  --member="serviceAccount:${GCP_RUNTIME_SA}" \
  --role="roles/secretmanager.secretAccessor" \
  --project="$GCP_PROJECT_ID" >/dev/null
note "on the secret, not the project — the runtime can read this and nothing else"
printf '\n'
pause "Press Enter to continue"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Hand the values to GitHub Actions"
say "Four values, none of them secret: a project id, a project number, two"
say "service account emails and a provider path. They go in as Actions"
say "variables rather than secrets precisely because they are not secrets, and"
say "a repository full of things marked secret that are not teaches nobody"
say "which ones matter."
printf '\n'
set_var GCP_PROJECT_ID   "$GCP_PROJECT_ID"
set_var GCP_WIF_PROVIDER "$GCP_WIF_PROVIDER"
set_var GCP_DEPLOY_SA    "$GCP_DEPLOY_SA"
set_var GCP_RUNTIME_SA   "$GCP_RUNTIME_SA"
printf '\n'
say "If any of those was skipped, set it by hand:"
note "  gh variable set GCP_PROJECT_ID   --body '$GCP_PROJECT_ID'"
note "  gh variable set GCP_WIF_PROVIDER --body '$GCP_WIF_PROVIDER'"
note "  gh variable set GCP_DEPLOY_SA    --body '$GCP_DEPLOY_SA'"
note "  gh variable set GCP_RUNTIME_SA   --body '$GCP_RUNTIME_SA'"
printf '\n'
pause "Press Enter for the summary"

finish

say "What exists now, and what it costs:"
step "two Cloud Run regions' worth of registry, empty until CI pushes an image"
step "two service accounts, neither able to do the other's job"
step "a federation trusting one GitHub repository, with no key anywhere"
step "one secret, which the switchover deletes"
printf '\n'
note "Nothing is running yet, so the project bills nothing. Push to main and"
note "the deploy workflow builds, scans, pushes and deploys to both regions."
printf '\n'
say "Then, from docs/hosting-the-calculator.md §13:"
step "step 3 — curl the two public URLs and prove a real forecast comes back"
step "step 4 — make forge-lint, and deploy the app to development"
step "step 5 — confirm FORGE_AUDIENCE, switch both services to forge-token"
step "step 6 — the atomic baseUrl commit"
printf '\n'
