// Generates src/assets.js: the Python runtime, the Python, and a memory
// snapshot, gzip-and-base64, for `src/runtime.js` to unpack inside the Forge
// function. Run by `make forge-assets`, which `make forge-deploy` depends on.
//
// Never committed. The Python is read straight out of agent/tools/ and
// service/ at generation time, so there is one copy of it; a committed
// assets.js would be a second copy of the calculator, and a second copy
// drifts. .gitignore names the file and the security suite asserts it does.
// ADR 0031.
//
// The snapshot is `makeMemorySnapshot()` after `loadPyodide({ _makeSnapshot })`,
// the sources written and BOOT run — the same BOOT `runtime.js` runs on a
// plain load, imported from there so the two cannot differ. A snapshot made
// here on macOS loads on Forge's Linux runtime with identical figures
// (docs/research/2026-09-02-second-probe-consumer-and-snapshot.md §2).
//
// Usage, from forge/:   node build-assets.mjs
import { createRequire } from 'node:module';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import { loadPyodide } from 'pyodide';

const require = createRequire(import.meta.url);
const { BOOT, writeSources } = require('./src/runtime.js');

const HERE = path.dirname(new URL(import.meta.url).pathname);
const ROOT = path.resolve(HERE, '..');
const PYODIDE = path.join(HERE, 'node_modules', 'pyodide');
const OUT = path.join(HERE, 'src', 'assets.js');

/** The five files the runtime needs, and nothing else the package ships. */
const RUNTIME_FILES = ['pyodide.mjs', 'pyodide.asm.mjs', 'pyodide.asm.wasm',
  'python_stdlib.zip', 'pyodide-lock.json'];

const pinned = JSON.parse(fs.readFileSync(path.join(HERE, 'package.json'), 'utf8'))
  .devDependencies?.pyodide;
const installed = JSON.parse(fs.readFileSync(path.join(PYODIDE, 'package.json'), 'utf8')).version;
if (pinned !== installed) {
  // An exact pin and the package on disk are two statements of one fact.
  console.error(`pyodide: package.json pins ${pinned}, node_modules has ${installed}. Run make forge-deps.`);
  process.exit(1);
}

// ---- the files, keyed by the path they unpack to --------------------------
const files = {};
for (const f of RUNTIME_FILES) files[`pyodide/${f}`] = fs.readFileSync(path.join(PYODIDE, f));

// The Python, laid out as routes.py expects: the tools two directories up
// from it under agent/tools/. Every .py in the tools directory, so a module
// added there ships without this file being edited — and nothing else, so a
// README or a snapshot beside them does not.
const sources = {};
for (const f of fs.readdirSync(path.join(ROOT, 'agent', 'tools')).sort()) {
  if (f.endsWith('.py')) sources[`agent/tools/${f}`] = fs.readFileSync(path.join(ROOT, 'agent', 'tools', f), 'utf8');
}
sources['service/routes.py'] = fs.readFileSync(path.join(ROOT, 'service', 'routes.py'), 'utf8');
for (const [name, text] of Object.entries(sources)) files[`work/${name}`] = Buffer.from(text, 'utf8');

// ---- the snapshot ---------------------------------------------------------
const t0 = performance.now();
const py = await loadPyodide({ indexURL: PYODIDE, _makeSnapshot: true });
writeSources(py, sources);
// Proved before it is snapshotted: a snapshot of a runtime that cannot answer
// is a deploy that fails inside a tenant.
const probe = JSON.parse(py.runPython(`answer_json('/v1/nope', '{}')`));
if (probe[0] !== 404) {
  console.error('the runtime did not answer before the snapshot was taken:', probe);
  process.exit(1);
}
const snapshot = py.makeMemorySnapshot();
files['snapshot.bin'] = Buffer.from(snapshot);
const snapMs = Math.round(performance.now() - t0);

// ---- the digest, and the module ------------------------------------------
// Content-addressed, so runtime.js unpacks a new bundle to a new directory
// and a warm /tmp from the previous deploy is never read by mistake.
const hash = crypto.createHash('sha256');
for (const name of Object.keys(files).sort()) { hash.update(name); hash.update(files[name]); }
const digest = hash.digest('hex').slice(0, 16);

let raw = 0;
let encoded = 0;
let out = '// GENERATED by forge/build-assets.mjs — never commit this file. ADR 0031.\n'
        + `// pyodide ${installed}; sources read from agent/tools/ and service/ at generation.\n`
        + `'use strict';\nmodule.exports = {\n  digest: ${JSON.stringify(digest)},\n  files: {\n`;
for (const [name, buf] of Object.entries(files)) {
  const b64 = zlib.gzipSync(buf, { level: 9 }).toString('base64');
  raw += buf.length;
  encoded += b64.length;
  out += `    ${JSON.stringify(name)}: ${JSON.stringify(b64)},\n`;
}
out += '  },\n};\n';
fs.writeFileSync(OUT, out);

const mb = (n) => (n / 1048576).toFixed(1);
console.log(`${path.relative(ROOT, OUT)}: ${Object.keys(files).length} files, ${mb(raw)} MB raw, `
          + `${mb(encoded)} MB encoded; snapshot ${mb(snapshot.length)} MB in ${snapMs} ms; `
          + `digest ${digest}; pyodide ${installed}, python ${py.runPython('import sys; sys.version.split()[0]')}`);
